### ISSUE TITLE
UMLS Authorized Download UI

### ISSUE THREAD

**Issue by shirey** [x-atlas-consortia/ubkg-download#1]
Create a new very simple UI with the following functionality:
  - When not logged in provide a login link, which when clicked will prompt the user for their UMLS license key and provide a message telling the user to go to https://uts.nlm.nih.gov to obtain a license key if they don't have one.
    - At login the user's license key will be authenticated/authorized against the new endpoint created in [ingest-api #541](https://github.com/hubmapconsortium/ingest-api/issues/541). 
    - On successful login the key should be stored in local storage or a cookie, expiring in 24 hours
    - On a failed login, the message "Invalid UMLS License Key.  Please obtain a valid license key at: https://uts.nlm.nih.gov"
  - When logged in:
    - echo the license key that the user is logged in under with a "logout" link
    - Show a list of files available for download with file name, size and (optional) description for each file.  This information will be available from the new endpoint created by [ingest-api #542](https://github.com/hubmapconsortium/ingest-api/issues/542)
      - Each file name should be linked to "https://assets.hubmapconsortium.org/umls-download/<file name>?umls-key=<umls-key>" for file download

  - provide a route from the UI `/download/<filename>` where:
    - it will check for a valid umls key in storage/cookie
      - if no valid key found, ask the user for a key and validate it
    - with a valid umls key redirect the browser to download the file from the assets service at `https://assets.hubmapconsortium.org/umls-download/<filename>?umls-key=<valid-umls-key>`

**Comment by yuanzhou** [comment]
Update 4/16/2024,

@BirdMachine we'll rename the ingest-api file list endpoint to `GET /ubkg-download-file-list`. So in the file assets URL, you'll change to `https://assets.hubmapconsortium.org/ubkg-download/<filename>?umls-key=<valid-umls-key>`
