### ISSUE TITLE
Add descriptive text and links to UBKG download

### ISSUE THREAD

**Issue by shirey** [x-atlas-consortia/ubkg-download#7]
For both logged in and logged out views: Add text explaining why we require a UMLS key for download and link to the page describing UMLS API Licensing: https://www.nlm.nih.gov/databases/umls.html.  The licensing issue arises because we include the UMLS inside of the UBKG database, which needs to be licensed.

For the logged out view- Add "To obtain a UMLS API License Key see: \<umls api license page\>"

**Comment by AlanSimmons** [comment]
# License requirements

The [Unified Biomedical Knowledge Graph (UBKG)](https://ubkg.docs.xconsortia.org/) includes content from biomedical vocabularies that are maintained by the [National Library of Medicine](https://uts.nlm.nih.gov/uts/umls/home). The use of content from the UMLS is governed by the [UMLS License Agreement](url).

Use of the UMLS content in the UBKG requires two licenses:
1. The University of Pittsburgh distributes content originating from the UMLS by means of a distributor license.
2. Consumers of the UBKG have access to UMLS content through the license that is part of their [UMLS Technology Services ](https://uts.nlm.nih.gov/uts/)(UTS) accounts. 

This site combines the API key from the University of Pittsburgh with the API key from a user to authenticate a user's request to download the UBKG. The user must provide the API for their UTS account to the UBKG Download site.

# To obtain a UTS API key

- Create a [UTS](https://uts.nlm.nih.gov/uts/) user profile
- Generate an API key.
